const MACHINE_PREPARE_TIME = 300;
const GRIND_TIME = 300;
const BREW_TIME = 500;
const BEANS_PER_BREW = 20;
const POWDER_PER_BREW = BEANS_PER_BREW * 10;

module.exports = {
    MACHINE_PREPARE_TIME,
    GRIND_TIME,
    BREW_TIME,
    BEANS_PER_BREW,
    POWDER_PER_BREW,
}